---
title: "Mass Shootings in the USA"
author: "Hannah Reitz & Sophie Hensgen"
date: "5/14/2020"
output: html_document
---

```{r}
library(openxlsx)
library(xml2)
library(rvest)
library(jsonlite)
library(robotstxt)
library(RSocrata)
library(dplyr)
library(rlist)
library(pipeR)

```
## Data from Wikipedia


```{r}
url <- "https://en.wikipedia.org/wiki/List_of_mass_shootings_in_the_United_States"
t <- read_html(url)
table <- t %>% html_nodes("#mw-content-text > div > table") %>% html_table(trim=T)

table

```

hier Tabellen zusammensetzten

erstes klappt, danach gibt es ein problem mit incompatiblen types. 
Ich glaube wir müssen die buchstaben aus injured rausholen damit wir es in einen integer umändern können

```{r}
newtab <- table[[1]]

newtab <- newtab %>% full_join(table[[2]], by = c("Date", "Location", "Dead", "Injured", "Total", "Description"))


class(newtab$Injured)
 
class(as.integer(table[[3]]$Injured))
table[[3]]$Injured
```

Wenn wir das geschafft haben sollten wir diesen Loop nutzen können
Zurzeit funktioniert er noch nicht
```{r}
new <- table[[1]]
for (i in 2:10){
  newtab <- newtab %>% full_join(table[[i]])
}

newtab
```








